% building this document: (in R) Sweave ("ctc.Rnw")
\documentclass[a4paper]{article}

\title{Amap Package}
\author{Antoine Lucas}
%\VignetteIndexEntry{Introduction to amap}
%\VignettePackage{amap}
\SweaveOpts{echo=FALSE}
%\usepackage{a4wide}

\begin{document}

\maketitle

\tableofcontents

\section{Overview}

{\tt Amap} package includes standard hierarchical  
clustering and k-means. We optimize implementation 
(with a parallelized hierarchical clustering) and
allow the possibility of using different distances like
Eulidean or Spearman (rank-based metric).

We implement a principal component analysis (with robusts methods).

We provide several functions for 
conversion. Specially to  import data from
Xcluster\footnote{http://genome-www.stanford.edu/\~\/sherlock/cluster.html} 
 or Cluster\footnote{http://rana.lbl.gov/EisenSoftware.htm} 
 software (very used for Gene's expression
analysis), and to export clusters to TreeView or Freeview visualization
software.

\section{Usage}

\subsection{Clustering}

The standard way of building  a hierarchical clustering:
<<echo=TRUE>>=
library(amap)
data(USArrests)
h = hcluster(USArrests)
plot(h)
@ 
 Or for the ``heatmap'':
<<echo=TRUE>>=
heatmap(as.matrix(USArrests),
        hclustfun=hcluster,
        distfun=function(u){u})
@ 
On a multiprocessor computer:
<<echo=TRUE>>=
h = hclusterpar(USArrests,nbproc=4)   
@ 
The K-means clustering:
<<echo=TRUE,results=hide>>=
Kmeans(USArrests,centers=3,method="correlation")
@ 

\subsection{Robust tools}

A robust variance computation:
<<echo=TRUE,results=hide>>=
data(lubisch)
lubisch <- lubisch[,-c(1,8)]
varrob(scale(lubisch),h=1)
@ 
A robust principal component analysis:
<<echo=TRUE,results=hide>>=
p <- acpgen(lubisch,h1=1,h2=1/sqrt(2))
plot(p)
@ 
Another robust pca:
<<echo=TRUE,results=hide>>=
p <- acprob(lubisch,h=4)
plot(p)
@ 

\subsection{Building hierarchical clustering with another software}

We made these tools
\begin{description}
\item[r2xcluster] Write data table to Xcluster file format 
<<echo=TRUE>>=
r2xcluster(USArrests,file='USArrests_xcluster.txt')
@ 
 \item[r2cluster] Write data table to Cluster file format 
<<echo=TRUE>>=
r2cluster(USArrests,file='USArrests_xcluster.txt')
@ 
\item[xcluster] Hierarchical clustering (need Xcluster tool  by Gavin Sherlock) 
\begin{verbatim}
> h.xcl=xcluster(USArrests)
> plot(h.xcl)
\end{verbatim}
 
It is roughtly the same as
\begin{verbatim}
> r2xcluster(USArrests,file='USArrests_xcluster.txt')
> system('Xcluster -f USArrests_xcluster.txt -e 0 -p 0 -s 0 -l 0')
> h.xcl=xcluster2r('USArrests_xcluster.gtr',labels=TRUE)
\end{verbatim}


\item[xcluster2r] Importing Xcluster/Cluster output 

\end{description}                 


\subsection{Using other visualization softwares}

We now consider that we have an object of the type produced by 'hclust'
(or a hierarchical cluster imported with previous functions) like:

<<echo=TRUE>>=
hr = hcluster(USArrests)
hc = hcluster(t(USArrests))
@ 



\begin{description}
\item[hc2Newick] Export hclust objects to Newick format files
<<echo=TRUE>>=
write(hc2Newick(hr),file='hclust.newick')
@ 
\item[r2gtr,r2atr,r2cdt] Export hclust objects to Freeview or Treeview
visualization softwares
<<echo=TRUE>>=
r2atr(hc,file="cluster.atr")
r2gtr(hr,file="cluster.gtr")
r2cdt(hr,hc,USArrests ,file="cluster.cdt")
@ 

\item[hclust2treeview] Clustering and Export hclust objects to Freeview or Treeview
visualization softwares 
<<echo=TRUE>>=
hclust2treeview(USArrests,file="cluster.cdt")
@ 
\end{description}



\section{See Also}

Theses examples can be tested with command
{\tt demo(amap)}.\\

\noindent
All functions has got man pages, try 
{\tt help.start()}.\\

\noindent
Robust tools has been published: \cite{caussinu+ruiz} and
\cite{caussinu+ruiz2}.

\noindent
Amap aims to interact with other softwares, some of them:
\begin{description}
\item[xcluster]
made  by Gavin Scherlock, http://genome-www.stanford.edu/\~\/sherlock/cluster.html
\item[Cluster, Treeview]
made  by Michael Eisen, http://rana.lbl.gov/EisenSoftware.htm
\item[Freeview]
made by Marco Kavcic and Blaz Zupan,
http://magix.fri.uni-lj.si/freeview
\end{description}                 



\bibliographystyle{plain}
\bibliography{amap}



\end{document}


